### ISSUE TITLE
안녕하세요!

### ISSUE THREAD

**Issue by lovevlq** [RWB0104/KorCham#3]
다름이아니라 사용법 관련해서 궁금한게 있는데요

Korcham 실행해서  jason 파일 생성 됐고, 3번 눌러서 url 리스트 출력했는데

제가 찾아보고자하는 url은 어디에 등록을 해야 하는지 잘 모르겠습니다..

jason이 설정파일인 줄 알고 클릭 했더니 아무 반응이 없어서 실행프로그램을 자바로 연동 시켜봤더니 이상한 파일이 켜지네요ㅠㅠ..

**Comment by RWB0104** [comment]
출력된 URL 리스트 열어보시면 지정하신 조건에 해당하는 시험장 URL이 표시될 것입니다.
URL 리스트 중 원하시는 시험장의 URL 주소를 복사하세요.

프로그램이 설치된 경로로 가시면 KorChamConf.json 파일이 있습니다.
해당 파일을 메모장으로 여시고 수정하시면 됩니다.

수정방법은 사용방법을 참고해주세요.
